#
# Setup travis for java, it auto detects gradle for most parts
#
language: java
sudo: false # faster builds

#
# Build / Test scripts
#
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  # - ./gradlew jar
  # - ./gradlew shadowJar
  # - ./gradlew fatJar
  
#
# Caching - to be used if relevent
#
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
#
# Code coverage run
#
after_success:
  - bash <(curl -s https://codecov.io/bash)